# Permalinks
permalink:        /:title

# Setup
title:            MyWeddingCars
tagline:          woderful classic cars for a wonderful day
description:      woderful classic cars for a wonderful day
url:              https://rogenhofer.com
baseurl:          
rawurl:
# Add this and create headline.html in _includes directory
# headline: true
# Add your google_analytics ID if you need it
# google_analytics:

# Pagination number
paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
